### ISSUE TITLE
possible typo in send function a-job-queue-in-bash.html

### ISSUE THREAD

**Issue by HarleyGolfGuy** [timtadh/hackthology#2]
Hi Tim, I love your 'job queue in bash' article.  I think there might be a typo in the 'send' function as the 'work_id' and 'work_item' are both set to $1 ... probably should be $1 and $2 respectively. 
 Thanks!  https://hackthology.com/a-job-queue-in-bash.html

**Comment by timtadh** [comment]
finally fixed this. Thank you for the bug report!!!
